In [ ]:
#pip install numpy

In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a[3]

4

In [7]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
np.zeros(2)

array([0., 0.])

In [15]:
np.ones(2)

array([1., 1.])

In [23]:
np.empty(3) # generates random numbers

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313])

In [24]:
np.arange(4) #create an array of a range of elements

array([0, 1, 2, 3])

In [26]:
np.arange(1,10,2) #create an array that contains a range of evenly spaced intervals.

array([1, 3, 5, 7, 9])

Specifying your data type

In [27]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [33]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
arr.ndim #To find the number of dimensions of the array.

1

In [35]:
arr.size #To find the total number of elements in the array.

8

In [36]:
# how do you interpret this output
arr.shape #To find the shape of your array.

(8,)

In [45]:
r=arr.reshape(4,2) #Give a new shape to an array without changing the data.
r

array([[2, 1],
       [5, 3],
       [7, 4],
       [6, 8]])

In [47]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [49]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [50]:
#select elements that are divisible by 3
a[a%3==0]

array([ 3,  6,  9, 12])

In [51]:
a[(a > 2) & (a < 11)] #select elements that satisfy two conditions using the & and | operators:

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
#Specify whether or not the values in an array fulfill a certain condition.
five_up = (a > 5) | (a == 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Basic array operations

In [53]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [54]:
a+b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [56]:
a-b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [57]:
a*b

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [58]:
a/b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
a.sum(axis=0)

array([15, 18, 21, 24])

# **Broadcasting**

**carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes.**

In [59]:
a*2.5

array([[ 2.5,  5. ,  7.5, 10. ],
       [12.5, 15. , 17.5, 20. ],
       [22.5, 25. , 27.5, 30. ]])

In [60]:
a+2.5

array([[ 3.5,  4.5,  5.5,  6.5],
       [ 7.5,  8.5,  9.5, 10.5],
       [11.5, 12.5, 13.5, 14.5]])

other useful functions

In [62]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],

              [0.54627315, 0.05093587, 0.40067661, 0.55645993],

              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [64]:
a.max()

0.82485143

In [66]:
b.max()

12

In [67]:
b.std()

3.452052529534663

In [68]:
b.mean()

6.5